name: Security

on:
  workflow_call:
    # Can be called by other workflows to run the formatting and linting steps

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1

      - name: Run zizmor 🌈
        run: uvx --no-progress zizmor --persona auditor --format plain .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}