name: Security

on:
  workflow_call:
    # Can be called by other workflows to run the formatting and linting steps

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - name: Run zizmor 🌈
        run: uvx --no-progress zizmor --persona auditor --format plain .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}